name: gigantier_sdk
description: SDK for Gigantier API
version: 1.0.8
author: Gigantier <ops@gigantier.com>
homepage: https://gigantier.com/
repository: https://github.com/Gigantier/flutter-sdk

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+1
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
